baseURL = 'https://ankita13-code.github.io/ankita-blogs/'
languageCode = 'en-us'
title = 'Ankita Pareek's blog'
theme = "m10c"

[params]
  author = "Ankita Pareek"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/Ankita13-code"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/ankita_pareek_"